"""empty message

Revision ID: 29eb2ad12012
Revises: bb20a714f284
Create Date: 2024-07-15 16:11:04.888237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29eb2ad12012'
down_revision = 'bb20a714f284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bussinessName', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bussinessPhoneNo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('bussinessPhoneNo')
        batch_op.drop_column('bussinessName')

    # ### end Alembic commands ###
