"""empty message

Revision ID: 8d098c514d1d
Revises: 29eb2ad12012
Create Date: 2024-07-15 17:53:11.042722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d098c514d1d'
down_revision = '29eb2ad12012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PaymentMode', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('PaymentMode')

    # ### end Alembic commands ###
